### ISSUE TITLE
gir files are Linux-only

### ISSUE THREAD

**Issue by matthewbauer** [gtk-rs/gir-files#35] opened 2019-04-21 02:47 UTC
These .gir files only work on Linux systems! For instance g_desktop_app_info_get_type is not available in macOS systems (g_osx_app_info_get_type is instead). Perhaps these files could be generated on the fly for each platform?

**Comment by GuillaumeGomez** [comment] 2019-04-21 08:09
I have to admit that I don't know how to support nicely such cases...

Any idea @EPashkin @sdroege ?

**Comment by EPashkin** [comment] 2019-04-21 08:22
`GOsxAppInfo` is separate class that replaces `GDesctopAppInfo` when  "HAVE_COCOA" defined.
It seems don't have even public constructor, only 2 function defined besides `g_osx_app_info_get_type`
```
GLIB_AVAILABLE_IN_2_52
char  * g_osx_app_info_get_filename       (GOsxAppInfo *info);

GLIB_AVAILABLE_IN_2_52
GList * g_osx_app_info_get_all_for_scheme (const gchar *scheme);
```
Last return list of `GAppInfo` interfaces and seems count as constructor.

So we can add cfg_condition "not(osx)" to `GDesctopAppInfo` and then implement `GOsxAppInfo` and its functions manually.

**Comment by sdroege** [comment] 2019-04-21 16:31
We have a similar problem in GStreamer with `GstGL-1.0.gir`, just worse. The API available there depends not only on the OS but also on the available GL platform(s). The way how we solved that there is by merging the XML parts of other platforms into one for the bindings, and via the .toml configuration of gir give each its own Cargo feature.

Works but is ugly, but I don't see a better solution for this with the current way how gobject-introspection works.

**Comment by samm-git** [comment] 2020-01-15 11:46
Also on macos it is causing issue with gio:

```
  "_g_desktop_app_info_get_implementations", referenced from:
      gio::auto::desktop_app_info::DesktopAppInfo::get_implementations::h39f8b9ded749059c in librsvg_c_api.a(gio-a9fe66c4b1029806.gio.6bhpekaq-cgu.7.rcgu.o)
  "_g_desktop_app_info_get_type", referenced from:
      _$LT$gio..auto..desktop_app_info..DesktopAppInfo$u20$as$u20$glib..types..StaticType$GT$::static_type::h1de2af8b073eef74 in librsvg_c_api.a(gio-a9fe66c4b1029806.gio.6bhpekaq-cgu.7.rcgu.o)
  "_g_desktop_app_info_new", referenced from:
      gio::auto::desktop_app_info::DesktopAppInfo::new::h7e539e264f012c4b in librsvg_c_api.a(gio-a9fe66c4b1029806.gio.6bhpekaq-cgu.7.rcgu.o)
  "_g_desktop_app_info_new_from_keyfile", referenced from:
      gio::auto::desktop_app_info::DesktopAppInfo::new_from_keyfile::hdd23e166fd1f7916 in librsvg_c_api.a(gio-a9fe66c4b1029806.gio.6bhpekaq-cgu.7.rcgu.o)
  "_g_desktop_app_info_search", referenced from:
      gio::desktop_app_info::_$LT$impl$u20$gio..auto..desktop_app_info..DesktopAppInfo$GT$::search::h194a199f99b5d7f6 in librsvg_c_api.a(gio-a9fe66c4b1029806.gio.6bhpekaq-cgu.7.rcgu.o)
```

These are Linux only and not defined in macos gio.

**Comment by sdroege** [comment] 2020-01-15 11:48
Can you create an issue against gio for that? Unfortunately there is no such information in the gir files so we need to manually configure that on our side.

**Comment by samm-git** [comment] 2020-01-15 11:52
Thank you for reply. I dont understand why it should be issue to gir. On my local file in the `~/gtk/inst/share/gir-1.0` there is no such functions, so i think the whole idea that gir-s must be same on all platforms is just nonsense.

**Comment by sdroege** [comment] 2020-01-15 11:56
The problem is that we need to generate the bindings once from a single .gir file as otherwise it would have to be generated every time and we would have no control over how broken your personal .gir files are and in what state they're in, and more importantly everybody would have their own version of the bindings and there would be no reproducability.

The problem with gobject-introspection is that it's not well-designed but it's the best and only thing we have right now, so we have to work around such things. Meaning in your specific case that in gio that specific API has to be marked as not available on macOS.

**Comment by samm-git** [comment] 2020-01-15 11:57
Got it. yes, gir is not very well designed. i see that you have already `#[cfg(any(not(windows), feature = "dox"))]` in the rs, probably same needed for macos for the g_desktop_app_info*. Will be happy to test that. For now its breaking librsvg

**Comment by sdroege** [comment] 2020-01-15 12:01
Yeah that's why I was asking you to create an issue for gio so that's being kept track of and can be fixed :)

**Comment by samm-git** [comment] 2020-01-15 12:04
Ah, so for gtk-rs/gio. not for glib/gio :)

**Comment by sdroege** [comment] 2020-01-15 12:05
Ah yes, sorry for not being more clear

**Comment by bilelmoussaoui** [comment] 2023-03-14 10:41
I guess this something we can close, as it is not really related to this repository and we can't do much about it with the current design of GIR. The best we  could do is manually implement those platform specific functions

**Closed by bilelmoussaoui** 2023-03-14 10:41 UTC
